[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.mypy]
disallow_untyped_defs = true  # Forces you to use type hints
enable_error_code = "ignore-without-code"  # Warn when a # type: ignore comment does not specify any error codes
ignore_missing_imports = true  # Ignores `import-untyped`
python_version = "3.14"
show_error_codes = true
strict = true
warn_return_any = true
warn_unused_configs = true

# --- ignore modules ---
[[tool.mypy.overrides]]
module = [
    'tests.unit_tests.*',
]
ignore_errors = true