name: Run Integration Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.py'
      - '**.pyw'
      - '.github/actions/get_conformance_suites_matrix/**'
      - '.github/actions/test_conformance_suite/**'
      - '.github/workflows/integration-tests.yml'
      - 'arelle_test_engine/**'
      - 'requirements*.txt'
      - 'tests/**'

permissions: {}

jobs:
  find-conformance-suites:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.build-conformance-suite-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6.0.2
      - id: build-conformance-suite-matrix
        uses: ./.github/actions/get_conformance_suites_matrix

  run-conformance-suite:
    name: ${{ matrix.test.short_name }}${{ matrix.test.shard && format(':{0}', matrix.test.shard) || '' }} - ${{ matrix.test.os }} - ${{ matrix.test.python_version }}
    needs: find-conformance-suites
    runs-on: ${{ matrix.test.os }}
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJson(needs.find-conformance-suites.outputs.matrix) }}
    # TODO: Skip private configs until integrated with Arelle or secrets added to this repo.
    # environment: ${{ matrix.test.environment }}
    steps:
      - name: Checkout Arelle
        uses: actions/checkout@v6.0.2
        with:
          repository: Arelle/Arelle
          ref: '2.38.12'
      - name: Checkout Arelle Test Engine
        uses: actions/checkout@v6.0.2
        with:
          path: arelle_test_engine
      - name: Install Arelle Test Engine Workflows & Tests
        shell: bash
        run: |
          rm -rf .github/*
          mv arelle_test_engine/.github/* .github/
          rm -rf tests/integration_tests/*
          mv arelle_test_engine/tests/integration_tests/* tests/integration_tests/
          rm -rf tests/plugin/*
          mv arelle_test_engine/tests/plugin/* tests/plugin/
      - name: Test Conformance Suite
        # TODO: Skip private configs until integrated with Arelle or secrets added to this repo.
        if: ${{ matrix.test.environment == 'none' }}
        uses: ./.github/actions/test_conformance_suite
        with:
          name: ${{ matrix.test.name }}
          python_version: ${{ matrix.test.python_version }}
          shard: ${{ matrix.test.shard }}
          short_name: ${{ matrix.test.short_name }}
